$directories = @(
    "assets/icons",
    "assets/images",
    "assets/logos",
    "assets/illustrations",
    "assets/fonts",
    "css/layouts",
    "css/components",
    "css/pages/public",
    "css/pages/seeker",
    "css/pages/employer",
    "js/layouts",
    "js/state",
    "js/services",
    "js/utils",
    "js/components/navbar",
    "js/components/sidebar",
    "js/components/buttons",
    "js/components/cards",
    "js/components/charts",
    "js/components/forms",
    "js/components/modals",
    "js/components/notifications",
    "js/components/forest",
    "js/views/public/landing",
    "js/views/public/auth",
    "js/views/seeker/dashboard",
    "js/views/seeker/roadmap",
    "js/views/seeker/profile",
    "js/views/seeker/ecosystem",
    "js/views/seeker/pods",
    "js/views/employer/dashboard",
    "js/views/employer/candidates",
    "js/views/employer/thresholds",
    "js/views/employer/analytics",
    "js/views/shared/errors",
    "js/views/shared/loading",
    "js/templates",
    "data",
    "docs"
)

$files = @(
    "index.html",
    "css/main.css",
    "css/reset.css",
    "css/variables.css",
    "css/animations.css",
    "css/layouts/public-layout.css",
    "css/layouts/seeker-layout.css",
    "css/layouts/employer-layout.css",
    "css/components/buttons.css",
    "css/components/cards.css",
    "css/components/forms.css",
    "css/components/modals.css",
    "css/components/navbar.css",
    "css/components/sidebar.css",
    "css/components/charts.css",
    "css/components/progress.css",
    "css/components/notifications.css",
    "css/pages/public/landing.css",
    "css/pages/public/about.css",
    "css/pages/public/pricing.css",
    "css/pages/public/features.css",
    "css/pages/public/auth.css",
    "css/pages/seeker/dashboard.css",
    "css/pages/seeker/roadmap.css",
    "css/pages/seeker/profile.css",
    "css/pages/seeker/ecosystem.css",
    "css/pages/seeker/pods.css",
    "css/pages/employer/employer-dashboard.css",
    "css/pages/employer/candidates.css",
    "css/pages/employer/thresholds.css",
    "css/pages/employer/analytics.css",
    "js/main.js",
    "js/router.js",
    "js/config.js",
    "js/layouts/publicLayout.js",
    "js/layouts/seekerLayout.js",
    "js/layouts/employerLayout.js",
    "js/state/store.js",
    "js/state/authState.js",
    "js/state/userState.js",
    "js/state/roadmapState.js",
    "js/state/employerState.js",
    "js/services/api.js",
    "js/services/authService.js",
    "js/services/userService.js",
    "js/services/roadmapService.js",
    "js/services/employerService.js",
    "js/services/aiService.js",
    "js/utils/helpers.js",
    "js/utils/validators.js",
    "js/utils/storage.js",
    "js/utils/date.js",
    "js/utils/notifications.js",
    "js/views/public/landing/homeView.js",
    "js/views/public/landing/aboutView.js",
    "js/views/public/landing/featuresView.js",
    "js/views/public/landing/pricingView.js",
    "js/views/public/landing/contactView.js",
    "js/views/public/auth/loginView.js",
    "js/views/public/auth/registerView.js",
    "js/views/public/auth/forgotPasswordView.js",
    "js/templates/loading.html",
    "js/templates/empty-state.html",
    "data/mockUsers.json",
    "data/mockRoadmaps.json",
    "data/mockEmployers.json",
    "docs/frontend-rules.md",
    "docs/naming-conventions.md",
    "docs/api-contracts.md",
    "docs/git-workflow.md"
)

foreach ($dir in $directories) {
    if (-not (Test-Path -Path $dir)) {
        New-Item -ItemType Directory -Path $dir | Out-Null
    }
}

foreach ($file in $files) {
    if (-not (Test-Path -Path $file)) {
        New-Item -ItemType File -Path $file | Out-Null
    }
}

Write-Host "Architecture created successfully."
